# Generated by Django 3.0.5 on 2020-09-14 11:58

from django.db import migrations, models
import util.views


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20200914_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='img_url',
            field=models.FileField(upload_to='pics', validators=[util.views.validate_file_size]),
        ),
    ]
