# Generated by Django 3.1 on 2020-08-29 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('special', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='special',
            name='img_url',
            field=models.FileField(null=True, upload_to='pics'),
        ),
    ]
