# Generated by Django 3.1 on 2020-08-30 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('special', '0002_special_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='special',
            name='status',
            field=models.BooleanField(null=True),
        ),
    ]
