# Generated by Django 3.0.5 on 2020-09-14 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('special', '0003_special_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='special',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
