# Generated by Django 3.0.5 on 2020-09-14 11:58

from django.db import migrations, models
import util.views


class Migration(migrations.Migration):

    dependencies = [
        ('special', '0004_auto_20200914_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='special',
            name='img_url',
            field=models.FileField(null=True, upload_to='pics', validators=[util.views.validate_file_size]),
        ),
    ]
