# Generated by Django 3.0 on 2020-08-12 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20200812_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='begin_day',
            field=models.CharField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='end_day',
            field=models.CharField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], max_length=20, null=True),
        ),
    ]
