# Generated by Django 3.0 on 2020-08-15 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_contact_contactmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='mobile_phone',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='photo_url',
        ),
    ]
