# Generated by Django 3.0 on 2020-08-16 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_auto_20200815_0814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmessage',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(max_length=1000),
        ),
    ]
