# Generated by Django 3.0.5 on 2020-08-22 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0009_auto_20200822_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='has_message',
            field=models.BooleanField(default=False),
        ),
    ]
