# Generated by Django 3.0.5 on 2020-09-07 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0011_auto_20200822_2138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='is_active',
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='response',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
