# Generated by Django 3.0.5 on 2020-08-22 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=100, null=True)),
                ('your_phone', models.CharField(max_length=15, null=True)),
                ('msgemail', models.EmailField(max_length=254, null=True)),
                ('book_date', models.DateTimeField(blank=True, null=True)),
                ('book_time', models.TimeField(null=True)),
                ('msg', models.TextField(blank=True, null=True)),
                ('persons_number', models.IntegerField(blank=True, null=True)),
                ('created_on', models.DateField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('modified_on', models.DateField(auto_now=True, null=True)),
                ('response', models.TextField(blank=True, null=True)),
                ('has_responded', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'verbose_name_plural': 'Book a Table',
            },
        ),
    ]
