# Generated by Django 3.0.5 on 2020-08-22 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='has_message',
            field=models.BooleanField(default=True),
        ),
    ]
