# Generated by Django 3.0.8 on 2020-08-15 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=100, null=True)),
                ('event_desc', models.TextField(max_length=1000, null=True)),
                ('event_img', models.FileField(upload_to='pics')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_on', models.DateField(auto_now_add=True, null=True)),
                ('status', models.BooleanField()),
                ('package', models.ManyToManyField(to='event.Package')),
            ],
            options={
                'verbose_name_plural': 'MenuItems',
            },
        ),
    ]
