# Generated by Django 3.0.8 on 2020-08-15 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerevents',
            options={'verbose_name_plural': 'Customer Events'},
        ),
        migrations.AlterModelOptions(
            name='package',
            options={'verbose_name_plural': 'Events'},
        ),
    ]
