# Generated by Django 3.0.8 on 2020-08-15 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20200815_0836'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventBackground',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_bg', models.FileField(upload_to='pics')),
            ],
            options={
                'verbose_name_plural': 'EventBackground',
            },
        ),
    ]
