# Generated by Django 3.0.8 on 2020-08-15 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_eventbackground'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='package',
            options={'verbose_name_plural': 'Packages'},
        ),
    ]
