# Generated by Django 3.0.5 on 2020-09-04 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_customerevents_tagline'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerevents',
            name='event_category',
            field=models.CharField(choices=[('Customer Event', 'Customer Event'), ('Restaurant Event', 'Restaurant Event')], default='Customer Event', max_length=50),
        ),
        migrations.AddField(
            model_name='customerevents',
            name='modified_on',
            field=models.DateField(auto_now=True),
        ),
    ]
