# Generated by Django 3.0.5 on 2020-09-04 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_auto_20200904_2255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerevents',
            options={'verbose_name_plural': 'Events'},
        ),
    ]
