# Generated by Django 3.0.5 on 2020-09-04 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_auto_20200904_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerevents',
            name='event_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerevents',
            name='event_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
