# Generated by Django 3.0.5 on 2020-09-04 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_auto_20200904_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerevents',
            name='event_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
