# Generated by Django 3.0.5 on 2020-09-04 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_auto_20200904_2348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerevents',
            name='event_time',
        ),
    ]
