# Generated by Django 3.0.5 on 2020-09-13 23:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_remove_customerevents_event_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerevents',
            name='created_on',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customerevents',
            name='event_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customerevents',
            name='event_type',
            field=models.CharField(default='type', max_length=100),
            preserve_default=False,
        ),
    ]
