# Generated by Django 3.0.5 on 2020-09-14 11:54

from django.db import migrations, models
import util.views


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_auto_20200913_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerevents',
            name='event_img',
            field=models.FileField(upload_to='pics', validators=[util.views.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='customerevents',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
