# Generated by Django 3.0.8 on 2020-08-10 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_menuitems'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitems',
            options={'verbose_name_plural': 'MenuItems'},
        ),
    ]
