# Generated by Django 3.0.8 on 2020-08-11 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_auto_20200811_2103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitems',
            old_name='img_url',
            new_name='menuImage',
        ),
    ]
