# Generated by Django 3.0.8 on 2020-08-10 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.FileField(upload_to='pics')),
                ('logo_url', models.FileField(null=True, upload_to='pics')),
                ('welcome_msg', models.CharField(max_length=200, null=True)),
                ('Tagline', models.CharField(max_length=200, null=True)),
                ('status', models.BooleanField()),
                ('created_on', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Background Images',
            },
        ),
    ]
