# Generated by Django 3.0.8 on 2020-08-10 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='backgroundimages',
            name='company_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
