# Generated by Django 3.0.8 on 2020-08-10 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_backgroundimages_company_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='backgroundimages',
            old_name='Tagline',
            new_name='restaurant_name',
        ),
        migrations.RenameField(
            model_name='backgroundimages',
            old_name='company_name',
            new_name='tagline',
        ),
    ]
