# Generated by Django 3.0.8 on 2020-08-10 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200810_1951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backgroundimages',
            name='welcome_msg',
        ),
    ]
