# Generated by Django 3.0.5 on 2020-09-04 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_backgroundimages_welcome_msg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.FileField(upload_to='pics')),
                ('status', models.BooleanField()),
                ('created_on', models.DateField(auto_now_add=True, null=True)),
                ('modified_on', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Gallery',
            },
        ),
        migrations.AddField(
            model_name='backgroundimages',
            name='modified_on',
            field=models.DateField(auto_now=True),
        ),
    ]
