# Generated by Django 3.0.5 on 2020-09-04 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200904_2000'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
