# Generated by Django 3.0.5 on 2020-09-14 09:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_delete_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundimages',
            name='created_on',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='backgroundimages',
            name='logo_url',
            field=models.FileField(default='url', upload_to='pics'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='backgroundimages',
            name='restaurant_name',
            field=models.CharField(default='restaurant', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='backgroundimages',
            name='tagline',
            field=models.CharField(default='tagline', max_length=200),
            preserve_default=False,
        ),
    ]
