# Generated by Django 3.0.5 on 2020-09-14 11:58

from django.db import migrations, models
import util.views


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200914_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundimages',
            name='img_url',
            field=models.FileField(upload_to='pics', validators=[util.views.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='backgroundimages',
            name='logo_url',
            field=models.FileField(upload_to='pics', validators=[util.views.validate_file_size]),
        ),
    ]
