# Generated by Django 3.0 on 2020-08-11 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoreValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('status', models.BooleanField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_on', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Core Values',
            },
        ),
        migrations.CreateModel(
            name='WhyUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('status', models.BooleanField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_on', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Why Us',
            },
        ),
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('vision', models.CharField(max_length=500, null=True)),
                ('mission', models.CharField(max_length=500, null=True)),
                ('img_url', models.FileField(upload_to='pics')),
                ('status', models.BooleanField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_on', models.DateField(auto_now_add=True, null=True)),
                ('core_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.CoreValue')),
            ],
            options={
                'verbose_name_plural': 'About Us',
            },
        ),
    ]
