# Generated by Django 3.0 on 2020-08-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_remove_corevalue_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whyus',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
