# Generated by Django 3.0 on 2020-08-12 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_auto_20200811_2338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='core_value',
        ),
    ]
