# Generated by Django 3.0 on 2020-08-20 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_corevalue_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corevalue',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
