# Generated by Django 3.0.5 on 2020-09-14 09:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0008_auto_20200820_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='created_on',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='mission',
            field=models.CharField(default='mission', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='title',
            field=models.CharField(default='title', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='vision',
            field=models.CharField(default='vision', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='corevalue',
            name='created_on',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='whyus',
            name='created_on',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='whyus',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='whyus',
            name='title',
            field=models.CharField(default='title', max_length=200),
            preserve_default=False,
        ),
    ]
