# Generated by Django 3.0.8 on 2020-08-10 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20200810_2209'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=100, null=True)),
                ('menu_desc', models.TextField(max_length=1000, null=True)),
                ('img_url', models.FileField(upload_to='pics')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_on', models.DateField(auto_now_add=True, null=True)),
                ('status', models.BooleanField()),
                ('menu_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.Menus')),
            ],
        ),
    ]
