# Generated by Django 3.0.5 on 2020-08-30 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_spetials'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_type', models.CharField(blank=True, max_length=100, null=True)),
                ('created_on', models.DateField(auto_now_add=True, null=True)),
                ('status', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'Menus',
            },
        ),
        migrations.RenameModel(
            old_name='Menus',
            new_name='MenuCategory',
        ),
        migrations.RenameField(
            model_name='menuitems',
            old_name='menus',
            new_name='menuCategory',
        ),
        migrations.AddField(
            model_name='menuitems',
            name='menuType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.MenuType'),
        ),
    ]
