# Generated by Django 3.0.5 on 2020-08-30 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_auto_20200830_1122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menutype',
            options={'verbose_name_plural': 'Menu Type'},
        ),
    ]
