# Generated by Django 3.0.5 on 2020-08-30 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_auto_20200830_1123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menucategory',
            options={'verbose_name_plural': 'Menu Category'},
        ),
        migrations.AlterModelOptions(
            name='menuitems',
            options={'verbose_name_plural': 'Menu Items'},
        ),
    ]
