# Generated by Django 3.0.5 on 2020-08-30 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_auto_20200830_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuCategoryType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_type', models.CharField(blank=True, max_length=100, null=True)),
                ('created_on', models.DateField(auto_now_add=True, null=True)),
                ('status', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'Menu Type',
            },
        ),
        migrations.RemoveField(
            model_name='menuitems',
            name='menuType',
        ),
        migrations.DeleteModel(
            name='MenuType',
        ),
        migrations.AddField(
            model_name='menuitems',
            name='MenuCategoryType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.MenuCategoryType'),
        ),
    ]
