# Generated by Django 3.0.5 on 2020-08-30 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0012_auto_20200830_1311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menucategorytype',
            options={'verbose_name_plural': 'Menu Category Type'},
        ),
    ]
