# Generated by Django 3.0.5 on 2020-08-30 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0013_auto_20200830_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menucategory',
            name='menu_category',
            field=models.CharField(choices=[('Food', 'Food'), ('Drink', 'Drink')], max_length=100),
        ),
    ]
