# Generated by Django 3.0.5 on 2020-08-30 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0015_auto_20200830_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrinkType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drinkType', models.CharField(blank=True, max_length=100, null=True)),
                ('created_on', models.DateField(auto_now_add=True, null=True)),
                ('status', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'drink Type',
            },
        ),
        migrations.CreateModel(
            name='MenuSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('time_range', models.CharField(blank=True, max_length=100, null=True)),
                ('created_on', models.DateField(auto_now_add=True, null=True)),
                ('status', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'Menu Schedule',
            },
        ),
        migrations.RemoveField(
            model_name='menusubcategory',
            name='MenuSubCategory',
        ),
        migrations.RemoveField(
            model_name='menuitems',
            name='menuSubCategory',
        ),
        migrations.AddField(
            model_name='menuitems',
            name='menu_category',
            field=models.CharField(choices=[('Starter', 'Starter'), ('Main Course', 'Main Course'), ('Dessert', 'Dessert'), ('Drink', 'Drink')], max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='MenuCategory',
        ),
        migrations.DeleteModel(
            name='MenuSubCategory',
        ),
        migrations.AddField(
            model_name='menuitems',
            name='menuSchedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.MenuSchedule'),
        ),
    ]
