# Generated by Django 3.0.5 on 2020-08-30 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0016_auto_20200830_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitems',
            name='drinkType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.DrinkType'),
        ),
    ]
