# Generated by Django 3.0.5 on 2020-08-30 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0017_menuitems_drinktype'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitems',
            name='childrenMenu',
            field=models.BooleanField(default=False),
        ),
    ]
