# Generated by Django 3.0.5 on 2020-09-14 09:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0019_auto_20200830_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinktype',
            name='created_on',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='drinktype',
            name='drinkType',
            field=models.CharField(default='drink', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menuitems',
            name='created_on',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menuitems',
            name='menuSchedule',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='menu.MenuSchedule'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menuitems',
            name='menu_category',
            field=models.CharField(choices=[('Starter', 'Starter'), ('Main Course', 'Main Course'), ('Course Meal', 'Course Meal'), ('Dessert', 'Dessert'), ('Drink', 'Drink')], default='category', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menuitems',
            name='menu_name',
            field=models.CharField(default='name', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menuitems',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='menuschedule',
            name='created_on',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menuschedule',
            name='name',
            field=models.CharField(default='name', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menuschedule',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='menuschedule',
            name='time_range',
            field=models.CharField(default='time range', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='spetials',
            name='created_on',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='spetials',
            name='name',
            field=models.CharField(default='name', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='spetials',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='spetials',
            name='tagline',
            field=models.TextField(default='tagline', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='spetials',
            name='title',
            field=models.TextField(default='title', max_length=200),
            preserve_default=False,
        ),
    ]
