# Generated by Django 3.0.5 on 2020-09-14 11:58

from django.db import migrations, models
import util.views


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0020_auto_20200914_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitems',
            name='menuImage',
            field=models.FileField(upload_to='pics', validators=[util.views.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='spetials',
            name='menuImage',
            field=models.FileField(upload_to='pics', validators=[util.views.validate_file_size]),
        ),
    ]
